### ISSUE TITLE
Pretrained weights for small and base

### ISSUE THREAD

**Issue by arthuremir** [wfs123456/CCTrans#11]
Hi! Thanks for the awesome work!

Can you please share the pretrained weights for small and base models? Or, if you don't have them, maybe you can share the code for pretraining? It would be very helpful for me!

Thank you in advance!

**Comment by wfs123456** [comment]
The pretrained weights of Twins is given in&nbsp;https://github.com/Meituan-AutoML/Twins, especially,&nbsp;ALTGVT-Small,&nbsp;ALTGVT-Base,&nbsp;ALTGVT-Large.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wfs123456/CCTrans"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 凌晨2:03
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wfs123456/CCTrans] Pretrained weights for small and base (Issue #11)





 
Hi! Thanks for the awesome work!
 
Can you please share the pretrained weights for small and base models? Or, if you don't have them, maybe you can share the code for pretraining? It would be very helpful for me!
 
***@***.***
 Thank you in advance!

**Comment by arthuremir** [comment]
Ah, thanks!

**Comment by arthuremir** [comment]
Hi!

Did you test small and base models? Seems like it fails with a shape mismatch at any input sizes.
Code snippet:
```

model = ALTGVT.alt_gvt_base(pretrained=False)

model.eval()

for img_size in range(50, 1500):
    inputs = torch.randn((1, 3, img_size, img_size))
    try:
        model(inputs)
        print('works fine', img_size)
    except:
        print('failed on', img_size)
```

**Comment by wfs123456** [comment]
Ah, I misunderstood what you meant. The previous link is the pertrained parameters of the backbone(ALTGVT of the paper Twins) of the CCTrans.&nbsp; If need the base or tiny model of CCTrans, u can retrain.&nbsp; But,&nbsp;

as far as I know, the results are not good.


---Original---
From: ***@***.***&gt;
Date: Fri, May 6, 2022 20:25 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wfs123456/CCTrans] Pretrained weights for small and base (Issue#11)




 
Hi!
 
Did you test small and base models? Seems like it fails with a shape mismatch at any input sizes.
 Code snippet:
  model = ALTGVT.alt_gvt_base(pretrained=False) model.eval() for img_size in range(50, 1500):     inputs = torch.randn((1, 3, img_size, img_size))     try:         model(inputs)         print('works fine', img_size)     except:         print('failed on', img_size)

**Comment by arthuremir** [comment]
Sorry, my first question is not directly related to second. (May be I should create another issue)

I'm trying to run small and base models from CCTrans (even without preloaded weights) and getting a shape mismatch. Large models successfully processes input sizes 256, 512, and 768, but small and base models fail on all of them. So may be there are some architecture issues?

**Comment by wfs123456** [comment]
This phenomenon is caused by different patch_size with 7. (detailed in Function Altgvt_small). 7 is not divided by 256, so change crop_size to 224.


---Original---
From: ***@***.***&gt;
Date: Fri, May 6, 2022 21:02 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wfs123456/CCTrans] Pretrained weights for small and base (Issue#11)




 
Sorry, my first question is not directly related to second. (May be I should create another issue)
 
I'm trying to run small and base models from CCTrans (even without preloaded weights) and getting a shape mismatch. Large models successfully processes input sizes 256, 512, and 768, but small and base models fails on all of them. So may be there are some architecture issues?

**Comment by arthuremir** [comment]
Do you mean that the small and base models should work correctly on the input with shape (1, 3, 224, 224)?

**Comment by arthuremir** [comment]
Do you mean that the small and base models should work correctly on the input with shape (1, 3, 224, 224)?

**Comment by arthuremir** [comment]
I'm asking because small and base models give shape mismatch on (1, 3, 224, 224).
