### ISSUE TITLE
您好，在运行test.py的时候，报错the following arguments are required: --model-path

### ISSUE THREAD

**Issue by 7ran** [wfs123456/CCTrans#13]
然后我在model-path那里加了个default写上了路径，怎么还是报这个错误呀，咋解决谢谢。

**Comment by 7ran** [comment]
不好意思，已解决

**Comment by cangyuanc** [comment]
请问是如何解决的呢？那个.npy文件如何生成

**Comment by wfs123456** [comment]
把你自己训练好的模型加载进去，，npy是生成的gt密度图，推理的是用不到，你可以注释掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 下午3:06
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [wfs123456/CCTrans] 您好，在运行test.py的时候，报错the following arguments are required: --model-path (Issue #13)




 
请问是如何解决的呢？那个.npy文件如何生成
