### ISSUE TITLE
你好，请问跑出来的结果是弱监督还是完全监督怎么判断呀，小白比较不懂。

### ISSUE THREAD

**Issue by 7ran** [wfs123456/CCTrans#14]

**Comment by wfs123456** [comment]
看你读取的 ground_truth 是 点监督(全监督，即每个人头标注的点位置)还是计数监督(弱监督，即一张图片人数的总和，并不知道每个人头的位置)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月20日(周五) 晚上8:25
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wfs123456/CCTrans] 你好，请问跑出来的结果是弱监督还是完全监督怎么判断呀，小白比较不懂。 (Issue #14)

**Comment by 7ran** [comment]
谢谢，一般下载的ShanghaiTech数据集就是点监督吧

**Comment by cjl09** [comment]
下载下来里面的GT是带位置的，你要看的是作者实现的时候取的是位置坐标还是人数.

**Comment by 7ran** [comment]
> 下载下来里面的GT是带位置的，你要看的是作者实现的时候取的是位置坐标还是人数.

好的 谢谢。

**Comment by 7ran** [comment]
> _No description provided._
