### ISSUE TITLE
你好，麻烦问一下关于密度图py文件的问题

### ISSUE THREAD

**Issue by 7ran** [wfs123456/CCTrans#15]
我在终端这样运行的
python vis_densityMap.py --image_path /home2/qr/datasets/ShanghaiTech/part_B_final/train_data/ground_truth/GT_IMG_100 --weight_path ./best_model_mae-57.49_epoch-2.pth
为什么输出的是
load transformer pretrained
not find image path!
这个image_path是这样的么请问 谢谢。

**Comment by wfs123456** [comment]
GT_IMG_100后面&nbsp; 为什么没有.jpg



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月20日(周一) 晚上7:36
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wfs123456/CCTrans] 你好，麻烦问一下关于密度图py文件的问题 (Issue #15)




 
我在终端这样运行的
 python vis_densityMap.py --image_path /home2/qr/datasets/ShanghaiTech/part_B_final/train_data/ground_truth/GT_IMG_100 --weight_path ./best_model_mae-57.49_epoch-2.pth
 为什么输出的是
 load transformer pretrained
 not find image path!
 这个image_path是这样的么请问 谢谢。

**Comment by 7ran** [comment]
您好，我还没懂您的意思，这个image_path具体路径的话应该怎么写，您能示范一下吗，不太清楚问题错在哪了，谢谢。

**Comment by 7ran** [comment]
试了好久也没成功，image_path大佬能给示范一下吗...一直报not find image path谢谢了！
