### ISSUE TITLE
您好，我想问下关于可视化的问题

### ISSUE THREAD

**Issue by zhukaijie98** [wfs123456/CCTrans#34]
![image](https://github.com/wfs123456/CCTrans/assets/134950446/6730646a-38ee-41df-8637-bc1b14b4b601)
FileNotFoundError: [Errno 2] No such file or directory: 'F:/shanghai tech/part_A_final/test_data/density_maps_constant15/IMG_100.npy'
这里并没有生成.npy文件，该怎么弄呢

**Comment by wfs123456** [comment]
gt的可视化你参考pred写一下，很简单的，我去年就毕业工作了，现在没时间搞这个了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月10日(周一) 凌晨0:40
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wfs123456/CCTrans] 您好，我想问下关于可视化的问题 (Issue #34)




 

 FileNotFoundError: [Errno 2] No such file or directory: 'F:/shanghai tech/part_A_final/test_data/density_maps_constant15/IMG_100.npy'

**Comment by zhukaijie98** [comment]
好嘞谢谢您
