### ISSUE TITLE
hello,can I chat with you by email? Thanks

### ISSUE THREAD

**Issue by 7ran** [wfs123456/CCTrans#8]

**Comment by wfs123456** [comment]
email address is presented in title！



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 20, 2022 16:22 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [wfs123456/CCTrans] hello,can I chat with you by email? Thanks (Issue#8)

**Comment by 7ran** [comment]
请问，Twins中的PCPVT能跑这个实验吗，小白。

**Comment by wfs123456** [comment]
可以，不过效果可能达不到原论文中那么好



---Original---
From: ***@***.***&gt;
Date: Wed, Apr 20, 2022 16:32 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wfs123456/CCTrans] hello,can I chat with you by email? Thanks(Issue #8)




 
请问，Twins中的PCPVT能跑这个实验吗，小白。

**Comment by 7ran** [comment]
具体应该怎么改阿 跑不太通呢 谢谢
